### ISSUE TITLE
리팩토링

### ISSUE THREAD

**Issue by jieun-dev1** [Couch-Coders/6th-music-be#14]
추후 리팩토링 고려하여 체크할 사항들 미리 푸시해둡니다. 

(1) 코드 가독성
-주석 제거 
-들여쓰기/줄맞춤
-중복 코드 제거 

 (2) SOLID 원칙 준수 
Service Controller 분리 

(3) 키 등 기밀정보가 git 에 누출되지 않는지 확인.

**Comment by dy-shin** [comment]
(4) 폴더 구조 
- 기능이 늘어나면 하나의 패키지에 너무 많은 파일들이 담길것 같은데 어떻게 분할할지 고민해보는것도 좋을 것 같습니다
- [참고](https://www.popit.kr/spring-guide-directory-%EA%B0%80%EC%9D%B4%EB%93%9C/)

* 쓸데 없는 소리긴한데, 읽어보지도 않은 책을 추천하는게 웃기긴 하지만 리팩토링 관련해서 이 책이 유명한 것 같아서 그냥 공유 차원에서 올렸습니다.
* [리팩터링 2판](http://www.yes24.com/Product/Goods/89649360)

**Comment by jieun-dev1** [comment]
아니요 나중에 참고하면 좋으니까요! 공유 감사해요 동윤님
